import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTranslation } from 'react-i18next';
import { ImageWithFallback } from '@/shared/components/image';
export const AboutSection = () => {
    const { t } = useTranslation();
    const paragraphs = t('sections.about.paragraphs', { returnObjects: true });
    const actions = t('sections.about.actions', { returnObjects: true });
    return (_jsx("section", { id: "about", className: "bg-surface py-32 px-8 text-text", children: _jsxs("div", { className: "mx-auto max-w-6xl", children: [_jsxs("div", { className: "mb-24 text-center", children: [_jsx("h2", { className: "text-5xl tracking-tight", style: { fontFamily: "'Playfair Display', serif" }, children: t('sections.about.title') }), _jsx("div", { className: "mt-6 h-px w-16 bg-text mx-auto" })] }), _jsxs("div", { className: "grid gap-16 md:grid-cols-[0.45fr,0.55fr] md:items-start", children: [_jsx("div", { className: "flex justify-center", children: _jsxs("div", { className: "relative aspect-square w-full max-w-md overflow-hidden rounded-3xl border border-border shadow-lg", children: [_jsx(ImageWithFallback, { src: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=600&fit=crop", alt: t('sections.about.imageAlt'), className: "h-full w-full object-cover" }), _jsx("span", { className: "pointer-events-none absolute inset-0 bg-gradient-to-t from-slate-900/20 to-transparent" })] }) }), _jsxs("div", { className: "space-y-8 text-lg leading-relaxed text-text/90", children: [paragraphs.map((paragraph, idx) => (_jsx("p", { children: paragraph }, idx))), _jsxs("div", { className: "flex flex-wrap gap-6 pt-4 text-sm font-medium", children: [_jsx("a", { href: "https://github.com", target: "_blank", rel: "noopener noreferrer", className: "inline-flex items-center gap-2 border-b border-border pb-1 text-link transition hover:border-linkHover hover:text-linkHover", children: actions.github }), _jsx("a", { href: "/resume.pdf", className: "inline-flex items-center gap-2 border-b border-border pb-1 text-link transition hover:border-linkHover hover:text-linkHover", children: actions.resume })] })] })] })] }) }));
};
